services:
  - type: web
    name: yordamchi-ai-namdtu-transport
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: OPENAI_EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: USE_VECTOR_SEARCH
        value: "true"
      - key: BUILD_VECTOR_INDEX_ON_STARTUP
        value: "false"
